### ISSUE TITLE
INVALID_FILE_HANDLE is incorrect in 64bit Windows

### ISSUE THREAD

**Issue by cosmo0920** [cosmo0920/windows-pr#13]
See: https://github.com/fluent/fluentd/issues/920#issuecomment-225178221

**Comment by phasis68** [comment]
Here is a possible patch

`INVALID_FILE_HANDLE = (1 << ['a'].pack('p').length*8) - 1`

**Comment by cosmo0920** [comment]
How about this patch? (Also included fixing test) https://github.com/cosmo0920/windows-pr/commit/3a86f096b3f7dea7e0e2fd11ece377f0a9511d47

**Comment by djberg96** [comment]
['a'].pack('P').length  > 4 ? "64Bit" : "32Bit"

**Comment by djberg96** [comment]
Looking at my win32-eventlog code you can check for JRuby like so:

    RUBY_PLATFORM == 'java' && ENV_JAVA['sun.arch.data.model'] == '64'
